draft(KodeArea,BanyakTroop) :- currentPlayer(X),
                                     nameOfPlayers(NOP),
                                     format('~w meletakkan ~w tentara tambahan di ~w.~n', [X, BanyakTroop, KodeArea]),
                                     getIdx(NOP,X,IDX),
                                     IDX == 1,
                                     numOfFreeSoldiersP1(FS1),
                                     Comparator is FS1 - BanyakTroop,
                                     Comparator >= 0,
                                     ownershipP1(OP1),
                                     areaCodename(KodeArea,_,AreaIDX),
                                     getElmt(OP1,AreaIDX,AmmOfPpl),
                                     AmmOfPpl > 0, % if not milik orang lain
                                     retractall(newAmm(_)),
                                     S1 is BanyakTroop + AmmOfPpl,
                                     asserta(newAmm(S1)),
                                     newAmm(NA),
                                     setEl(OP1,AreaIDX,NA,NewLis),
                                     retractall(ownershipP1(_)),
                                     asserta(ownershipP1(NewLis)),
                                     retractall(soldiersLeft(_)),
                                     Subtraction is FS1 - BanyakTroop,
                                     asserta(soldiersLeft(Subtraction)),
                                     soldiersLeft(SL),
                                     retractall(numOfFreeSoldiersP1(_)),
                                     asserta(numOfFreeSoldiersP1(SL)),
                                     write('terdapat '),
                                     write(SL),
                                     write(' yang tersisa. ').
draft(KodeArea,BanyakTroop) :- currentPlayer(X),
                                     nameOfPlayers(NOP),
                                     format('~w meletakkan ~w tentara tambahan di ~w.~n', [X, BanyakTroop, KodeArea]),
                                     getIdx(NOP,X,IDX),
                                     IDX == 2,
                                     numOfFreeSoldiersP2(FS2),
                                     Comparator is FS2 - BanyakTroop,
                                     Comparator >= 0,
                                     ownershipP2(OP2),
                                     areaCodename(KodeArea,_,AreaIDX),
                                     getElmt(OP2,AreaIDX,AmmOfPpl),
                                     AmmOfPpl > 0,
                                     retractall(newAmm(_)),
                                     Hasil is BanyakTroop + AmmOfPpl,
                                     asserta(newAmm(Hasil)),
                                     newAmm(NA),
                                     setEl(OP2,AreaIDX,NA,NewLis),
                                     retractall(ownershipP2(_)),
                                     asserta(ownershipP2(NewLis)),
                                     retractall(soldiersLeft(_)),
                                     Subtraction is FS2 - BanyakTroop,
                                     asserta(soldiersLeft(Subtraction)),
                                     soldiersLeft(SL),
                                     retractall(numOfFreeSoldiersP2(_)),
                                     asserta(numOfFreeSoldiersP2(SL)),
                                     write('terdapat '),
                                     write(SL),
                                     write(' yang tersisa. ').